version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/api"
      - "/tfctl"
    labels: ["area/ci", "dependencies"]
    schedule:
      interval: "weekly"
    groups:
      go-patch:
        update-types:
        - "patch"
      go-minor:
        update-types:
        - "minor"
      go-major:
        update-types:
        - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-patch:
        update-types:
        - "patch"
      gh-minor:
        update-types:
        - "minor"
      gh-major:
        update-types:
        - "major"

